# Generated by Django 5.0.1 on 2024-02-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('model_name', models.CharField(max_length=200)),
                ('model_type', models.CharField(blank=True, max_length=200, null=True)),
                ('welcome_message', models.TextField()),
                ('prompt_start', models.TextField(blank=True, null=True)),
                ('parse_mode', models.CharField(blank=True, default='html', max_length=200, null=True)),
                ('extra_field', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat Mode',
                'verbose_name_plural': 'Chat Modes',
                'db_table': 'chat_mode',
            },
        ),
        migrations.CreateModel(
            name='GptModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200, unique=True)),
                ('config', models.JSONField()),
            ],
            options={
                'verbose_name': 'Gpt Model',
                'verbose_name_plural': 'Gpt Models',
                'db_table': 'gpt_models',
            },
        ),
        migrations.CreateModel(
            name='Subscribtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.FloatField()),
                ('n_tokens', models.IntegerField()),
                ('n_images', models.IntegerField()),
                ('n_tts', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Subscribtion',
                'verbose_name_plural': 'Subscribtions',
                'db_table': 'subscribtion',
            },
        ),
        migrations.CreateModel(
            name='TokenPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.FloatField()),
                ('n_tokens', models.IntegerField()),
                ('n_images', models.IntegerField()),
                ('n_tts', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Token Package',
                'verbose_name_plural': 'Token Packages',
                'db_table': 'token_package',
            },
        ),
        migrations.CreateModel(
            name='TextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('key', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Text Model',
                'verbose_name_plural': 'Text Models',
                'db_table': 'text_model',
                'unique_together': {('name', 'key')},
            },
        ),
    ]
