# Generated by Django 5.0.1 on 2024-01-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_bot', '0002_alter_chatgptuser_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgptuser',
            name='user_token',
            field=models.CharField(blank=True, default='2fe47a8d7f5d4e988b91357487c140dc', max_length=255, null=True),
        ),
    ]
