# Generated by Django 5.0.1 on 2024-01-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_bot', '0003_alter_chatgptuser_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgptuser',
            name='user_token',
            field=models.CharField(blank=True, default='4d1b2ead9be54f1b9fc729d9b75f5802', max_length=255, null=True),
        ),
    ]
