# Generated by Django 5.0.1 on 2024-02-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatgpt_bot", "0004_chatgptuser_language_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="dialog",
            name="input_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dialog",
            name="output_tokens",
            field=models.IntegerField(default=0),
        ),
    ]
