# Generated by Django 5.0.1 on 2024-01-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_bot', '0004_alter_chatgptuser_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgptuser',
            name='user_token',
            field=models.CharField(blank=True, default='6f929ef4f8404fc492fa068bfc6fabc8', max_length=255, null=True),
        ),
    ]
