# Generated by Django 5.0.1 on 2024-02-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatgpt_bot", "0006_messages_dialog_msg_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dialog",
            name="end",
            field=models.BooleanField(default=False),
        ),
    ]
