# Generated by Django 5.0.1 on 2024-02-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_bot', '0011_alter_dialog_chat_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages_dialog',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messages_dialog',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
