# Generated by Django 5.0.1 on 2024-02-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_bot', '0013_alter_chatgptuser_current_chat_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages_dialog',
            name='end',
            field=models.BooleanField(default=True),
        ),
    ]
