# Generated by Django 5.0.1 on 2024-02-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_bot', '0014_messages_dialog_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages_dialog',
            name='end',
            field=models.BooleanField(default=False),
        ),
    ]
