# Generated by Django 5.0.1 on 2024-02-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_bot', '0015_alter_messages_dialog_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages_dialog',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
