# Generated by Django 5.0.1 on 2024-02-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_bot', '0017_remove_messages_dialog_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgptuser',
            name='daily_limit',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='chatgptuser',
            name='extra_limit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
