# Generated by Django 5.0.1 on 2024-02-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_bot', '0019_chatgpttokens_logsenderbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_mode',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
