# Generated by Django 5.0.1 on 2024-02-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_main_setup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramProfile',
        ),
    ]
