# Generated by Django 5.0.1 on 2024-02-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_main_setup', '0002_backupsenderbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambot',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
