# Generated by Django 5.0.1 on 2024-02-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_killer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_sign',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
