# Generated by Django 5.0.1 on 2024-01-25 20:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGptUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_id', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('current_dialog_id', models.UUIDField(blank=True, default=None, null=True)),
                ('current_chat_mode', models.CharField(default='assistant', max_length=255)),
                ('current_model', models.CharField(max_length=255)),
                ('n_used_tokens', models.JSONField(default=dict)),
                ('n_generated_images', models.IntegerField(default=0)),
                ('n_transcribed_seconds', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.telegramprofile', verbose_name='Telegram User')),
            ],
            options={
                'verbose_name': 'ChatGpt User',
                'verbose_name_plural': 'ChatGpt Users',
            },
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_mode', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(max_length=255)),
                ('messages', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatgpt.chatgptuser')),
            ],
            options={
                'verbose_name': 'Dialog',
                'verbose_name_plural': 'Dialogs',
            },
        ),
    ]
