# Generated by Django 5.0.1 on 2024-01-25 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0005_telegrambot_app_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGptUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chat ID')),
                ('last_interaction', models.DateTimeField(auto_now=True, verbose_name='Last Interaction')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='First Seen')),
                ('curent_dialog_id', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Current Dialog ID')),
                ('current_chat_mode', models.CharField(blank=True, default='assistant', max_length=255, null=True, verbose_name='Current Chat Mode')),
                ('current_model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Current Model')),
                ('n_used_tokens', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of used tokens')),
                ('n_generated_images', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of generated images')),
                ('n_transcribed_seconds', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of transcribed seconds')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.telegramprofile', unique=True, verbose_name='Telegram User')),
            ],
            options={
                'verbose_name': 'ChatGpt User',
                'verbose_name_plural': 'ChatGpt Users',
            },
        ),
    ]
