# Generated by Django 5.0.1 on 2024-01-25 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0002_alter_chatgptuser_current_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgptuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='chatgptuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='chatgptuser',
            name='username',
        ),
    ]
