# Generated by Django 5.0.1 on 2024-01-25 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0003_remove_chatgptuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='chat_mode',
            field=models.CharField(default='assistant', max_length=255),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='messages',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='model',
            field=models.CharField(choices=[('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('gpt-3.5-turbo-16k', 'GPT-3.5 Turbo 16k'), ('gpt-4-1106-preview', 'GPT-4 1106 Preview'), ('gpt-4', 'GPT-4'), ('text-davinci-003', 'Text Davinci 003')], default='gpt-3.5-turbo', max_length=255),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatgpt.chatgptuser', verbose_name='ChatGpt User'),
        ),
    ]
