# Generated by Django 5.0.1 on 2024-01-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0004_alter_dialog_chat_mode_alter_dialog_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgptuser',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
