# Generated by Django 5.0.1 on 2024-01-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0005_alter_chatgptuser_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgptuser',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
