# Generated by Django 5.0.1 on 2024-01-28 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0006_alter_chatgptuser_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(blank=True, max_length=200, null=True)),
                ('welcome_message', models.TextField()),
                ('prompt_start', models.TextField(blank=True, null=True)),
                ('parse_mode', models.CharField(blank=True, default='html', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_base', models.CharField(blank=True, max_length=200, null=True)),
                ('new_dialog_timeout', models.IntegerField(blank=True, default=600, null=True)),
                ('return_n_generated_images', models.IntegerField(default=1)),
                ('n_chat_modes_per_page', models.IntegerField(default=5)),
                ('image_size', models.CharField(default='512x512', max_length=200)),
                ('enable_message_streaming', models.BooleanField(default=True)),
                ('chatgpt_price_per_1000_tokens', models.FloatField(default=0.006)),
                ('gpt_price_per_1000_tokens', models.FloatField(default=0.002)),
                ('whisper_price_per_1_min', models.FloatField(default=0.006)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GptModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('config', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='chatgptuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatgptuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chatgptuser',
            name='user_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
