# Generated by Django 5.0.1 on 2024-01-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0007_chat_mode_config_gptmodels_chatgptuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgptuser',
            name='last_interaction',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
