# Generated by Django 5.0.1 on 2024-01-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0008_alter_chatgptuser_last_interaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat_mode',
            old_name='name',
            new_name='key',
        ),
        migrations.AddField(
            model_name='chat_mode',
            name='model_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
