# Generated by Django 5.0.1 on 2024-01-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0009_rename_name_chat_mode_key_chat_mode_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='messages',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
