# Generated by Django 5.0.1 on 2024-01-29 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_telegramprofile_language'),
        ('chatgpt', '0010_alter_dialog_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgptuser',
            name='current_dialog_id',
        ),
        migrations.AddField(
            model_name='dialog',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.telegrambot'),
        ),
    ]
