# Generated by Django 5.0.1 on 2024-01-29 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0013_messages_dialog_dialog_created_at_dialog_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='messages',
        ),
        migrations.AddField(
            model_name='messages_dialog',
            name='dialog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatgpt.dialog'),
        ),
    ]
