# Generated by Django 5.0.1 on 2024-01-25 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('bot_token', models.CharField(max_length=255)),
                ('bot_username', models.CharField(blank=True, max_length=125, null=True)),
                ('app_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveBigIntegerField()),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(choices=[('uz', 'Uzbek')], default='uz', max_length=255, null=True)),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.telegrambot')),
            ],
        ),
    ]
