# Generated by Django 5.0.1 on 2024-01-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
