# Generated by Django 4.2 on 2023-04-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='language',
            field=models.CharField(choices=[('uz', 'Uzbek')], default='uz', max_length=255, null=True),
        ),
    ]
