# Generated by Django 5.0.1 on 2024-01-21 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_telegramprofile_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('bot_token', models.CharField(max_length=255)),
                ('bot_username', models.CharField(blank=True, max_length=125, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='telegramprofile',
            name='bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.telegrambot'),
        ),
    ]
