# Generated by Django 5.0.1 on 2024-01-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_telegrambot_telegramprofile_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='telegram_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
