# Generated by Django 5.0.1 on 2024-01-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_telegramprofile_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='app_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
