# Generated by Django 5.0.1 on 2024-01-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_telegrambot_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambot',
            name='app_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
